### ISSUE TITLE
Zero request ID value causes server crash

### ISSUE THREAD

**Issue by x1unix** [sangaman/http-jsonrpc-server#19]
Hello.

Recently I found an issue when zero `id` value in request causes server crash with message:

```
/project-dir/node_modules/http-jsonrpc-server/lib/http-jsonrpc-server.js:218
    if (this.onResult && response.result) {
                                  ^

TypeError: Cannot read properties of undefined (reading 'result')
    at CustomRpcServer.processRequest (/Users/x1unix/work/blockchain-data-provider/node_modules/http-jsonrpc-server/lib/http-jsonrpc-server.js:218:35)
    at CustomRpcServer.processRequest (/Users/x1unix/work/blockchain-data-provider/src/rpc/Server.js:43:32)
    at IncomingMessage.<anonymous> (/Users/x1unix/work/blockchain-data-provider/node_modules/http-jsonrpc-server/lib/reqhandler.js:124:12)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

```

**Request payload:**

```json
{
	"id": 0,
	"jsonrpc": "2.0",
	"method": "any-valid-method-name"
}
```

**Comment by sangaman** [comment]
Hello! Thanks for the bug report. I'll have a fix and a new version that includes it shortly.
